server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  profiles:
    active: @profileActive@
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  output:
    ansi:
      enabled: always


easy-query:
  #对象属性和数据库列名的转换器
  name-conversion: underlined
  # 是否启用追踪
  default-track: true
  #如果执行物理删除delete语句将会报错 如果改为false,后续可以通过allowDeleteStatment来允许
  deleteThrow: false
  #打印sql显示(需要框架默认有日志以 log.info打印)
  print-sql: true
  #sqlNativeSegment输入和格式化无需处理单引号会自动处理为双单引号
  keep-native-style: true
  #entity映射到dto/vo使用属性匹配模式
  #支持 property_only column_only column_and_property property_first
  mapping-strategy: property_first



# knife4j的增强配置
knife4j:
  enable: true
  # 是否生产环境，默认false，可以访问接口文档
  production: false
  setting:
    language: zh_cn
# springdoc-openapi项目配置
springdoc:
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '人脸'
      paths-to-match: '/**'
      packages-to-scan: com.nicesoftware.face.api.controller


logging:
  level:
    com.easy.query.core: info